//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Client.MusicPlayerServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicPlayerServices.IPlayerService")]
    public interface IPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTracks", ReplyAction="http://tempuri.org/IPlayerService/GetTracksResponse")]
        System.Collections.ObjectModel.ObservableCollection<MusicPlayer.Entities.Track> GetTracks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerService/GetTracks", ReplyAction="http://tempuri.org/IPlayerService/GetTracksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<MusicPlayer.Entities.Track>> GetTracksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerServiceChannel : MusicPlayer.Client.MusicPlayerServices.IPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServiceClient : System.ServiceModel.ClientBase<MusicPlayer.Client.MusicPlayerServices.IPlayerService>, MusicPlayer.Client.MusicPlayerServices.IPlayerService {
        
        public PlayerServiceClient() {
        }
        
        public PlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MusicPlayer.Entities.Track> GetTracks() {
            return base.Channel.GetTracks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<MusicPlayer.Entities.Track>> GetTracksAsync() {
            return base.Channel.GetTracksAsync();
        }
    }
}
